RASP_SERVER/config/routes.rb
Rails.application.routes.draw do
  resources :alarm_actions
  resources :settings
  #get 'welcome/index'
  root 'welcome#index'
  resources :alarms

  get 'get_alarm', to: "welcome#get_alarm"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RASP_SERVER/app/controllers/alarm_actions_controller.rb
class AlarmActionsController < ApplicationController
  before_action :set_alarm_action, only: [:show, :edit, :update, :destroy]

  # GET /alarm_actions
  # GET /alarm_actions.json
  def index
    @alarm_actions = AlarmAction.all
  end

  # GET /alarm_actions/1
  # GET /alarm_actions/1.json
  def show
  end

  # GET /alarm_actions/new
  def new
    @alarm_action = AlarmAction.new


  end

  # GET /alarm_actions/1/edit
  def edit
  end

  # POST /alarm_actions
  # POST /alarm_actions.json
  def create
    @alarm_action = AlarmAction.new(alarm_action_params)

    if params[:alarm_action][:from]=='home'
      if @alarm_action.save
        redirect_to root_path
      else
        redirect_to root_path
      end
    else
      respond_to do |format|
        if @alarm_action.save
          format.html { redirect_to @alarm_action, notice: 'Alarm action was successfully created.' }
          format.json { render :show, status: :created, location: @alarm_action }
        else
          format.html { render :new }
          format.json { render json: @alarm_action.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  # PATCH/PUT /alarm_actions/1
  # PATCH/PUT /alarm_actions/1.json
  def update
    respond_to do |format|
      if @alarm_action.update(alarm_action_params)
        format.html { redirect_to @alarm_action, notice: 'Alarm action was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm_action }
      else
        format.html { render :edit }
        format.json { render json: @alarm_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarm_actions/1
  # DELETE /alarm_actions/1.json
  def destroy
    @alarm_action.destroy
    respond_to do |format|
      format.html { redirect_to alarm_actions_url, notice: 'Alarm action was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm_action
      @alarm_action = AlarmAction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_action_params
      params.require(:alarm_action).permit(:disable_alarm)
    end
end

RASP_SERVER/app/helpers/alarm_actions_helper.rb
module AlarmActionsHelper
end

RASP_SERVER/app/views/alarm_actions/_form.html.erb
<%= form_with(model: alarm_action, local: true) do |form| %>
  <% if alarm_action.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alarm_action.errors.count, "error") %> prohibited this alarm_action from being saved:</h2>

      <ul>
      <% alarm_action.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :disable_alarm %>
    <%= form.check_box :disable_alarm %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RASP_SERVER/app/views/alarm_actions/edit.html.erb
<h1>Editing Alarm Action</h1>

<%= render 'form', alarm_action: @alarm_action %>

<%= link_to 'Show', @alarm_action %> |
<%= link_to 'Back', alarm_actions_path %>

RASP_SERVER/app/views/alarm_actions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alarm Actions</h1>

<table>
  <thead>
    <tr>
      <th>Disable alarm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alarm_actions.each do |alarm_action| %>
      <tr>
        <td><%= alarm_action.disable_alarm %></td>
        <td><%= link_to 'Show', alarm_action %></td>
        <td><%= link_to 'Edit', edit_alarm_action_path(alarm_action) %></td>
        <td><%= link_to 'Destroy', alarm_action, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alarm Action', new_alarm_action_path %>

RASP_SERVER/app/views/alarm_actions/new.html.erb
<h1>New Alarm Action</h1>

<%= render 'form', alarm_action: @alarm_action %>

<%= link_to 'Back', alarm_actions_path %>

RASP_SERVER/app/views/alarm_actions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Disable alarm:</strong>
  <%= @alarm_action.disable_alarm %>
</p>

<%= link_to 'Edit', edit_alarm_action_path(@alarm_action) %> |
<%= link_to 'Back', alarm_actions_path %>