RASP_SERVER/config/routes.rb
Rails.application.routes.draw do
  resources :alarm_actions
  resources :settings
  #get 'welcome/index'
  root 'welcome#index'
  resources :alarms

  get 'get_alarm', to: "welcome#get_alarm"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RASP_SERVER/app/models/alarm.rb
class Alarm < ApplicationRecord


	def self.should_alarm_go_off(request_url)
		is_reminder = false
		@setting = Setting.first
		timezone = @setting.timezone_hours_diff
		current_time = Time.now.utc + timezone.hours

		current_hour = current_time.hour
		current_min = current_time.min

		week_day_string = ""
		if (current_time.wday == 1)
			week_day_string = "repeat_monday"
		end
		if (current_time.wday == 2)
			week_day_string = "repeat_tuesday"
		end
		if (current_time.wday == 3)
			week_day_string = "repeat_wednesday"
		end
		if (current_time.wday == 4)
			week_day_string = "repeat_thursday"
		end
		if (current_time.wday == 5)
			week_day_string = "repeat_friday"
		end
		if (current_time.wday == 6)
			week_day_string = "repeat_saturday"
		end
		if (current_time.wday == 0)
			week_day_string = "repeat_sunday"
		end

		alarm_should_go_off = false
		alarm = Alarm.where(hour: current_hour, min:current_min).where( "#{week_day_string}": true )

		if alarm.count > 0
			alarm_should_go_off = true

			alarm.each do |a|
				if a.reminder == true	
					is_reminder = true
				else 
					is_reminder = false
				end
			end
		end

		alarm = Alarm.where(hour: current_hour, min:current_min).where( "#{week_day_string}": false ).where('created_at > ?', 24.hours.ago)
		
		if alarm.count > 0
			alarm_should_go_off = true
		
			alarm.each do |a|
				if a.reminder == true	
					is_reminder = true
				else 
					is_reminder = false
				end
				a.destroy
			end
		end




		str_return = "-1,-1,"
		if alarm_should_go_off
			if (@setting.operation_type == "Open Window and Play Song")
				str_return = "1,"+(@setting.minutes_to_next_action*60).to_s+","

				@last_action = AlarmAction.last
				if (@last_action)
					@last_action.disable_alarm = false
					@last_action.save
				end
			end
			if (@setting.operation_type == "Only Open Window")
				str_return = "1,-1,"
			end
			if (@setting.operation_type == "Only Play Song")
				str_return = "-1,1,"

				@last_action = AlarmAction.last
				if (@last_action)
					@last_action.disable_alarm = false
					@last_action.save
				end
			end
		end

		audio_url = nil
		if (@setting.mp3)
			audio_url = request_url + @setting.mp3.url
		end

		if (str_return == "-1,-1,")
			@last_action = AlarmAction.last
			if (@last_action)

				disable_alarm = @last_action.disable_alarm
				if (disable_alarm)
					@last_action.destroy
					str_return = "-1,-2,"
				end
			end
		end


		if is_reminder == true	
			str_return = "-1,-10,"
		end

		str_return = str_return + audio_url


		# "-1,1,audio_url" -> no_window, audio_next_second, audio_url
		# "1,1,audio_url"  -> window_next_second, audio_next_second, audio_url
		# "1,60,audio_url" -> window_next_second, audio_next_60_seconds, audio_url
		# "1,-1,audio_url" -> window_next_second, no_audio, audio_url

		return str_return #{enable: alarm_should_go_off, audio_url:audio}
	end


end

RASP_SERVER/app/models/alarm_action.rb
class AlarmAction < ApplicationRecord
end

RASP_SERVER/app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]

  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    # puts("******PARAMS:")
    # puts(params)
    # puts(params[:alarm])
    # puts(params[:alarm][:from])
    # #params.has_key?("hour") ? puts(params[:hour]) : puts("no hour")

    @alarm = Alarm.new(alarm_params)

    #@user_id = params.has_key?("user_id") ? params[:user_id] | current_user.id

    

    if params[:alarm][:from]=='home'
      if @alarm.save
        redirect_to root_path
      else
        redirect_to root_path
      end
    else
      respond_to do |format|
        if @alarm.save
          format.html { redirect_to @alarm, notice: 'Alarm was successfully created.' }
          format.json { render :show, status: :created, location: @alarm }
        else
          format.html { render :new }
          format.json { render json: @alarm.errors, status: :unprocessable_entity }
        end
      end
    end


  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.html { redirect_to @alarm, notice: 'Alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy

    if params[:from]=='home'
      redirect_to root_path
    else
      respond_to do |format|
        format.html { redirect_to alarms_url, notice: 'Alarm was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_params
      params.require(:alarm).permit(:hour, :min, :repeat_monday, :repeat_tuesday, :repeat_wednesday, :repeat_thursday, :repeat_friday, :repeat_saturday, :repeat_sunday, :reminder)
    end
end

RASP_SERVER/app/helpers/alarms_helper.rb
module AlarmsHelper
end

RASP_SERVER/app/views/alarms/_form.html.erb
<%= form_with(model: alarm, local: true) do |form| %>
  <% if alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :hour %>
    <%= form.number_field :hour %>
  </div>

  <div class="field">
    <%= form.label :min %>
    <%= form.number_field :min %>
  </div>

  <div class="field">
    <%= form.label :repeat_monday %>
    <%= form.check_box :repeat_monday %>
  </div>

  <div class="field">
    <%= form.label :repeat_tuesday %>
    <%= form.check_box :repeat_tuesday %>
  </div>

  <div class="field">
    <%= form.label :repeat_wednesday %>
    <%= form.check_box :repeat_wednesday %>
  </div>

  <div class="field">
    <%= form.label :repeat_thursday %>
    <%= form.check_box :repeat_thursday %>
  </div>

  <div class="field">
    <%= form.label :repeat_friday %>
    <%= form.check_box :repeat_friday %>
  </div>

  <div class="field">
    <%= form.label :repeat_saturday %>
    <%= form.check_box :repeat_saturday %>
  </div>

  <div class="field">
    <%= form.label :repeat_sunday %>
    <%= form.check_box :repeat_sunday %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RASP_SERVER/app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

RASP_SERVER/app/views/alarms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alarms</h1>

<table>
  <thead>
    <tr>
      <th>Hour</th>
      <th>Min</th>
      <th>Repeat monday</th>
      <th>Repeat tuesday</th>
      <th>Repeat wednesday</th>
      <th>Repeat thursday</th>
      <th>Repeat friday</th>
      <th>Repeat saturday</th>
      <th>Repeat sunday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alarms.each do |alarm| %>
      <tr>
        <td><%= alarm.hour %></td>
        <td><%= alarm.min %></td>
        <td><%= alarm.repeat_monday %></td>
        <td><%= alarm.repeat_tuesday %></td>
        <td><%= alarm.repeat_wednesday %></td>
        <td><%= alarm.repeat_thursday %></td>
        <td><%= alarm.repeat_friday %></td>
        <td><%= alarm.repeat_saturday %></td>
        <td><%= alarm.repeat_sunday %></td>
        <td><%= link_to 'Show', alarm %></td>
        <td><%= link_to 'Edit', edit_alarm_path(alarm) %></td>
        <td><%= link_to 'Destroy', alarm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alarm', new_alarm_path %>

RASP_SERVER/app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Back', alarms_path %>

RASP_SERVER/app/views/alarms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hour:</strong>
  <%= @alarm.hour %>
</p>

<p>
  <strong>Min:</strong>
  <%= @alarm.min %>
</p>

<p>
  <strong>Repeat monday:</strong>
  <%= @alarm.repeat_monday %>
</p>

<p>
  <strong>Repeat tuesday:</strong>
  <%= @alarm.repeat_tuesday %>
</p>

<p>
  <strong>Repeat wednesday:</strong>
  <%= @alarm.repeat_wednesday %>
</p>

<p>
  <strong>Repeat thursday:</strong>
  <%= @alarm.repeat_thursday %>
</p>

<p>
  <strong>Repeat friday:</strong>
  <%= @alarm.repeat_friday %>
</p>

<p>
  <strong>Repeat saturday:</strong>
  <%= @alarm.repeat_saturday %>
</p>

<p>
  <strong>Repeat sunday:</strong>
  <%= @alarm.repeat_sunday %>
</p>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> |
<%= link_to 'Back', alarms_path %>