RASP_SERVER/config/routes.rb
Rails.application.routes.draw do
  resources :alarm_actions
  resources :settings
  #get 'welcome/index'
  root 'welcome#index'
  resources :alarms

  get 'get_alarm', to: "welcome#get_alarm"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RASP_SERVER/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@alarms = Alarm.all
  	@setting = Setting.first
  end

  def get_alarm
  	render json: Alarm.should_alarm_go_off(request.base_url)
  end
end

RASP_SERVER/app/helpers/welcome_helper.rb
module WelcomeHelper
end

RASP_SERVER/app/views/welcome/index.html.erb
<!--<!DOCTYPE html>
<html>
    <head>
        <title>Weather Clock</title>
        <meta name="author" content="Alexander Kavanaugh">
    </head>
    <body>-->
        <div id="sb-site">
            <p>Alarm Clock</p>
            <div id="clockdiv">
            	<span hidden class="timezone hidden"><%= @setting.timezone_hours_diff%></span>
            	<h1 class="title" id="clock"><span class="hours">00</span>:<span class="minutes">00</span>:<span class="seconds">00</span></h1>
        	</div>
        	
        	<script>
        		function initializeClock(id) {
				var clock = document.getElementById(id);
				//alert(clock);
				var timezoneSpan = clock.querySelector('.timezone').innerHTML;
				var hoursSpan = clock.querySelector('.hours');
				var minutesSpan = clock.querySelector('.minutes');
				var secondsSpan = clock.querySelector('.seconds');


				function updateClock() {

				var t = Date.parse(new Date());
				var seconds = Math.floor((t / 1000) % 60);
				var minutes = Math.floor((t / 1000 / 60) % 60);
				var hours = Math.floor(((t / (1000 * 60 * 60)) + parseInt(timezoneSpan)) % 24);


				hoursSpan.innerHTML = ('0' + hours).slice(-2);
				minutesSpan.innerHTML = ('0' + minutes).slice(-2);
				secondsSpan.innerHTML = ('0' + seconds).slice(-2);

				if (t.total <= 0) {
				  clearInterval(timeinterval);
				}
				}

				updateClock();
				var timeinterval = setInterval(updateClock, 1000);
				}

				initializeClock('clockdiv');
        	</script>
        </div>

        <div id="alarms_content" class="sb-slidebar sb-right sb-style-push sb-width-custom" data-sb-width="100%">
            <div class="row">
            

                <%= link_to edit_setting_path(Setting.first) , method: :get, class: "btn btn-default sb-toggle-right", id:"sidebar_toggle_inner" do %>
	            	<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
	            <% end %>

                <div class="col-xs-12">
                    <div class="row alarm_header">
                        <div class="row">
                            <div class="col-12">
                                <h4>
                                    </br>
                                    <%= form_for AlarmAction.new do |form| %>
                                        <%= hidden_field_tag "alarm_action[from]", "home" %>
                                        <%= hidden_field_tag "alarm_action[disable_alarm]", true %>
                                        <%= form.submit "Stop Alarm" %>
                                    <% end %>
                                    </br>
                                </h4>
                                <h1 class="alarm_title text-center">Alarms</h1>
                            </div>
                            <br/>
                            <br/>
                            <br/>



							
								<!--
                                <h1 class="alarm_title">
                                |HOUR| |MIN| new alarm info to add... &nbsp; &nbsp;
                            	</h1>
                            	-->
								<%= form_for Alarm.new do |form| %>
									<%= hidden_field_tag "alarm[from]", "home" %>
									Hour: <%= form.number_field :hour, min: 0, max: 24 %> 
									Min: <%= form.number_field :min, min: 0, max: 60 %> |
									M: <%= form.check_box :repeat_monday %> | 
									T: <%= form.check_box :repeat_tuesday %> | 
									W: <%= form.check_box :repeat_wednesday %> | 
									T: <%= form.check_box :repeat_thursday %> | 
									F: <%= form.check_box :repeat_friday %> | 
									S: <%= form.check_box :repeat_saturday %> | 
									S: <%= form.check_box :repeat_sunday %> | 
                                    Reminder: <%= form.check_box :reminder %> | &nbsp;
									<%= form.submit %>
								<% end %>
                          	
                          	<!--
                            <div class="col-xs-4 text-right">
                                <<button type="button" class="btn btn-default" id="add_alarm_button">Add Alarm</button>
                          	</div>
                          -->
                          	<br/>
                            <br/>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3" id="add_alarm" style="display: none;">
                                <form class="form-inline" name="add_alarm_form" id="add_alarm_form">
                                    <div class="form-group">
                                        <label for="alarm_name" class="sr-only">Name</label>
                                      <input type="text" class="form-control" id="alarm_name" placeholder="Name" required=true />
                                    </div>
                                    <div class="form-group">
                                      <label for="alarm_timepicker" class="sr-only">Time</label>
                                      <div class='input-group date' id='alarm_timepicker'>
                                          <input type='text' id="alarm_time" placeholder="Click the clock -->" class="form-control" required=true/>
                                          <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span>
                                          </span>
                                      </div>
                                    </div>
                                    <button type="button" class="btn btn-default" onclick="add_alarm($('#alarm_name').val(), $('#alarm_time').val())">Add</button>
                                    <button type="reset" class="btn btn-default" onclick="$('#add_alarm').slideUp();">Cancel</button>
                                  </form>
                            </div>
                        </div>
                    </div>
                    <div class="row clearfix">
                        <table class="table" id="alarm_table">
                            <tbody>
                                <tr id="alarm_row">
                                	<% if @alarms.count == 0 %>
                                    	<td colspan=4>No Alarms Set</td>
                                    <% else %>
                                    	<tr>
                                    	<th>Reminder</th>
                                    	<th>Hour</th>
                                    	<th>Days of the week</th>
                                    	<th></th>
                                    	<tr/>
                                    	<% @alarms.each do |alarm| %>
                                			<tr>
	                                			<% 
	                                			days_string = "   "
	                                			if alarm.repeat_monday
	                                				days_string = days_string + " Mon |"
	                                			end
	                                			if alarm.repeat_tuesday
	                                				days_string = days_string + " Tue |"
	                                			end
	                                			if alarm.repeat_wednesday
	                                				days_string = days_string + " Wed |"
	                                			end
	                                			if alarm.repeat_thursday
	                                				days_string = days_string + " Thu |"
	                                			end
	                                			if alarm.repeat_friday
	                                				days_string = days_string + " Fri |"
	                                			end
	                                			if alarm.repeat_saturday
	                                				days_string = days_string + " Sat |"
	                                			end
	                                			if alarm.repeat_sunday
	                                				days_string = days_string + " Sun |"
	                                			end
	                                			%>

	                                			<td colspan=1>
	                                    			<%= alarm.reminder%>
	                                    		</td>
	                                    		<td colspan=1>
	                                    			<%= alarm.hour.to_s.rjust(2, '0') %>:<%= alarm.min.to_s.rjust(2, '0')%>
	                                    		</td>
	                                    		<td colspan=1>
	                                    			<%=days_string%>
	                                    		</td>
	                                    		<td colspan=1>
	                                    			<td>
	                                    				<%= link_to alarm_path(alarm, from:"home") , method: :delete, data: { confirm: 'Are you sure you want to delete this alarm?' }, class: "btn btn-default" do %>
	                                    						<i class="glyphicon glyphicon-minus"></i>
	                                    				<% end %>
	                                    			</td>
	                                    		</td>
                                    		</tr>

                                    	<% end %>
                                    <% end %>
                                </tr>
                             </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
<!--    </body>
</html>-->



<!--
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
-->