RASP_SERVER/config/routes.rb
Rails.application.routes.draw do
  resources :alarm_actions
  resources :settings
  #get 'welcome/index'
  root 'welcome#index'
  resources :alarms

  get 'get_alarm', to: "welcome#get_alarm"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RASP_SERVER/app/models/setting.rb
class Setting < ApplicationRecord

	has_attached_file :mp3
	validates_attachment_content_type :mp3, content_type: ["audio/mp3", "audio/mpeg"]#, content_type: {content_type: ["audio/mpeg", "audio/mp3"]}#, file_name: { :matches => [/mp3\z/] }

end

RASP_SERVER/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:operation_type, :minutes_to_next_action, :timezone_hours_diff, :mp3)
    end
end

RASP_SERVER/app/helpers/settings_helper.rb
module SettingsHelper
end

RASP_SERVER/app/views/settings/_form.html.erb
<%= form_with(model: setting, local: true) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  </br>
  <div class="field">
    <%= form.label :operation_type %>
    <br/>
    <!--< %= form.text_field :operation_type %>-->
    <%= form.radio_button :operation_type, 'Open Window and Play Song' %> Open Window and Play Song <br />
    <%= form.radio_button :operation_type, 'Only Open Window' %> Only Open Window <br />
    <%= form.radio_button :operation_type, 'Only Play Song' %> Only Play Song <br />
  </div>

  </br>
  <div class="field">
    <%= form.label :minutes_to_next_action %>
    <br/>
    <%= form.number_field :minutes_to_next_action %>
  </div>

  </br>
  <div class="field">
    <%= form.label :timezone_hours_diff %>
    <br/>
    <%= form.number_field :timezone_hours_diff %>
  </div>

  </br>
  <div class="field">
    <%= form.label :mp3, "New MP3 - Current Audio: #{setting.mp3_file_name}" %>
    <br/>
    <%= form.file_field :mp3%>
  </div>

  </br>
  <div class="actions">
    <br/>
    <%= form.submit %>
  </div>
<% end %>

RASP_SERVER/app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

</hr>
<!--< %= link_to 'Show', @setting %> | -->
<%= link_to 'Go Back', root_path %>

RASP_SERVER/app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>Operation type</th>
      <th>Minutes to next action</th>
      <th>Timezone hours diff</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.operation_type %></td>
        <td><%= setting.minutes_to_next_action %></td>
        <td><%= setting.timezone_hours_diff %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

RASP_SERVER/app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

RASP_SERVER/app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Operation type:</strong>
  <%= @setting.operation_type %>
</p>

<p>
  <strong>Minutes to next action:</strong>
  <%= @setting.minutes_to_next_action %>
</p>

<p>
  <strong>Timezone hours diff:</strong>
  <%= @setting.timezone_hours_diff %>
</p>

<p>
  <strong>Song Name:</strong>
  <%= @setting.mp3_file_name %>
</p>

<!-- < %= link_to 'Edit', edit_setting_path(@setting) %> | -->
<%= link_to 'Go Back', root_path %>